In [10]:
import numpy as np
import scipy as sp
from scipy.spatial.transform import Rotation as R

In [25]:
T = np.array([[-1, 0, 0, 20],
             [0, 0, -1, 8],
             [0, -1, 0, 2],
             [0, 0, 0, 1]])
T_inv = np.linalg.inv(T)
print(T_inv)
world_homo = np.array([18.9, 5.1, 3.7, 1.0])
camera_homo = T_inv @ world_homo
print(camera_homo)

[[-1. -0. -0. 20.]
 [-0. -0. -1.  2.]
 [-0. -1. -0.  8.]
 [ 0.  0.  0.  1.]]
[ 1.1 -1.7  2.9  1. ]


In [16]:
q = np.array([0.0, -0.707, 0.707, 0.0])

# get rotation matrix from q
rotation = R.from_quat(q)

print(rotation.as_matrix())

# get determinant of the matrix
print(np.linalg.det(rotation.as_matrix()))

[[-1. -0.  0.]
 [ 0.  0. -1.]
 [ 0. -1.  0.]]
1.0000000000000007
